### ISSUE TITLE
IDEA Support

### ISSUE THREAD

**Issue by LeoVS09** [Arkweid/lefthook#95]
I using Jetbrains Webstorm and lefthook not working for me. 
When I run commit through Webstorm 
Commit failing with 
```bash
Commit failed with error
 0 files committed, 6 files failed to commit: add generation top menu based on version of permissions
 .git/hooks/pre-commit: 7: .git/hooks/pre-commit: cannot open /dev/tty: No such device or address
```
Run on linux mint

When run by `git commit` in the terminal all working

**Comment by Arkweid** [comment]
Hi, @LeoVS09 could you try it on `v0.6.5`? We have some changes in 0.6.6 about pty interface.

**Comment by jonekdahl** [comment]
Hi @Arkweid, I see the same error with 0.6.6 and IDEA on Ubuntu Linux. Reverting to 0.6.5 and reinstalling hooks (`bundle exec lefhook install -f`) fixes the problem for me.

**Comment by LeoVS09** [comment]
Was test multiple version, before each version install I delete `.git/hooks` and `node_modules`
* For versions `v0.6.3` and `v0.6.5` hooks did not work at all from Webstorm, only work from the console
* For version `v0.6.6` failed with `/dev/tty` error
---
Also, we having the same error when running `git commit` in our Jenkins pipeline

**Comment by LeoVS09** [comment]
Am I not sure about changes between versions, but you can give version without changes in pty interface, but with other hooks install updates? Maybe it will work

**Comment by perifer** [comment]
My team also run into this. I guess interactive interactive pre-commit scripts are tricky if you are using a GUI.

Some things we also noticed: In my GUI of choice, GitUp, I don't get the `cannot open /dev/tty: No such device or address` error when commiting.  PHPStorm (which should be identical to WebStorm) get the error.

In both GitUp and PHPStorm we got the tty-error when using the GUI to push code. Not a big problem since we usually use the command line to push.

**Comment by yoannmoinet** [comment]
I have the same error in VSCode as well.

**Comment by Arkweid** [comment]
Going to fix that on this wekeend!

**Comment by Arkweid** [comment]
Fixed in 0.6.7
Works well in my VS Code editor. Let me know if problem exists in any other IDE

**Comment by juslintek** [comment]
@Arkweid problem still exists in PhpStorm, seems like it is not exiting push. Even if tests fail.

**Comment by RashiqAzhan** [comment]
Still broken in webstorm when trying to commit and push using the GUI.
```
╭──────────────────────────────────────╮
│ 🥊 lefthook v2.1.0  hook: pre-commit │
╰──────────────────────────────────────╯
┃  lint:fix ❯ 
sh: line 1: npm: command not found
exit status 127┃  typecheck ❯ 
sh: line 1: npm: command not found
exit status 127                
```

`git commit -m "commit message"` works just fine.

**Comment by RashiqAzhan** [comment]
Disregard, please. This was due to a misconfiguration in the IDE. The `npm` path under *Languages & Frameworks -> Node.js* was empty. I guess the GUI is using its own environment and not the terminal for its duties.
